name: Spell Check

on: [push, pull_request]

permissions:
  contents: write

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install cheerio glob

      - name: Strip visible HTML text (allow Italian)
        run: node scripts/remove-html-strings.js

      - name: Remove PHP strings (especially Italian)
        run: node scripts/remove-php-strings.js

      - name: Remove all string literals from selected JS files
        run: node scripts/remove-js-strings.js

      - name: Spell check
        uses: check-spelling/check-spelling@v0.0.25
        with:
          extra_dictionaries: |
            cspell:scala/dict/scala.txt
            cspell:css/dict/css.txt
            cspell:java/src/java-terms.txt
            cspell:typescript/dict/typescript.txt
            cspell:html/dict/html.txt
          extra_excludes: |
            (^|/)expect\.txt$
