name: Spell Check

on: [push, pull_request]

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Spell Check
        uses: check-spelling/check-spelling@v0.0.74
        with:
          check-spelling-dictionaries: en
          check-spelling-wordlists: .github/wordlists/tech.txt
          check-spelling-fail-on-unrecognized: true
