name: Image Optimization

on:
  push:
    branches:
      - main
      - '**'
    paths:
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.png'
      - '**/*.webp'
      - '**/*.avif'
  pull_request:
    paths:
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.png'
      - '**/*.webp'
      - '**/*.avif'

jobs:
  optimize-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compress images in PR
        uses: calibreapp/image-actions@main
        with:
          jpegQuality: '85'
          pngQuality: '80'
          webpQuality: '85'
          avifQuality: '75'
          ignorePaths: 'node_modules/**,dist/**'
          commitMessage: 'Optimize images'
          commit: true
