name: Super-Linter

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2 Psalm error check
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: pdo, pdo_mysql

      - name: Install Composer dependencies
        run: |
            cd src
            composer install --no-interaction --no-cache --classmap-authoritative=false


      - name: Run Psalm
        run: |
            cd src
            vendor/bin/psalm --output-format=github


      # 3 Run Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          LOG_LEVEL: WARN
          VALIDATE_JSCPD: false
          VALIDATE_PHP: false
          VALIDATE_PHP_PSALM: false
          FILTER_REGEX_EXCLUDE: "vendor/.*|node_modules/|dist/|build/"

      # 4 Run JSCPD
      - name: Run JSCPD
        run: |
          npx jscpd \
            --threshold 10 \
            --min-lines 5 \
            --min-tokens 50 \
            --ignore "**/node_modules/**,**/dist/**,**/build/**"
