name: Super-Linter

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2 Build custom Super-Linter image with PDO
      - name: Build custom Super-Linter with PDO
        run: docker build -t superlinter-pdo .github/superlinter

      - name: Debug PHP version inside Super-Linter
        run: |
          docker run github/super-linter:latest php -v


      # 3 Run Super-Linter using the custom image
      - name: Run Super-Linter
        run: |
          docker run \
            -e RUN_LOCAL=true \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e VALIDATE_ALL_CODEBASE=false \
            -e LOG_LEVEL=WARN \
            -e VALIDATE_JSCPD=false \
            -e VALIDATE_PHP=false \
            -e FILTER_REGEX_EXCLUDE="vendor/.*|node_modules/|dist/|build/" \
            -v ${{ github.workspace }}:/tmp/lint \
            superlinter-pdo

      # 4 Run JSCPD
      - name: Run JSCPD
        run: |
          npx jscpd \
            --threshold 10 \
            --min-lines 5 \
            --min-tokens 50 \
            --ignore "**/node_modules/**,**/dist/**,**/build/**"
